// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: implant.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	In            string                 `protobuf:"bytes,1,opt,name=In,proto3" json:"In,omitempty"`
	Out           string                 `protobuf:"bytes,2,opt,name=Out,proto3" json:"Out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_implant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_implant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_implant_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

func (x *Command) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_implant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_implant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_implant_proto_rawDescGZIP(), []int{1}
}

type ImplantData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	LastSeen      string                 `protobuf:"bytes,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImplantData) Reset() {
	*x = ImplantData{}
	mi := &file_implant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImplantData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplantData) ProtoMessage() {}

func (x *ImplantData) ProtoReflect() protoreflect.Message {
	mi := &file_implant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplantData.ProtoReflect.Descriptor instead.
func (*ImplantData) Descriptor() ([]byte, []int) {
	return file_implant_proto_rawDescGZIP(), []int{2}
}

func (x *ImplantData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImplantData) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *ImplantData) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

func (x *ImplantData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ImplantsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Implants      []*ImplantData         `protobuf:"bytes,1,rep,name=implants,proto3" json:"implants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImplantsList) Reset() {
	*x = ImplantsList{}
	mi := &file_implant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImplantsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImplantsList) ProtoMessage() {}

func (x *ImplantsList) ProtoReflect() protoreflect.Message {
	mi := &file_implant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImplantsList.ProtoReflect.Descriptor instead.
func (*ImplantsList) Descriptor() ([]byte, []int) {
	return file_implant_proto_rawDescGZIP(), []int{3}
}

func (x *ImplantsList) GetImplants() []*ImplantData {
	if x != nil {
		return x.Implants
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_implant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_implant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_implant_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_implant_proto protoreflect.FileDescriptor

const file_implant_proto_rawDesc = "" +
	"\n" +
	"\rimplant.proto\x12\agrpcapi\"+\n" +
	"\aCommand\x12\x0e\n" +
	"\x02In\x18\x01 \x01(\tR\x02In\x12\x10\n" +
	"\x03Out\x18\x02 \x01(\tR\x03Out\"\a\n" +
	"\x05Empty\"q\n" +
	"\vImplantData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\tR\blastSeen\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"@\n" +
	"\fImplantsList\x120\n" +
	"\bimplants\x18\x01 \x03(\v2\x14.grpcapi.ImplantDataR\bimplants\"\"\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xac\x01\n" +
	"\aImplant\x120\n" +
	"\fFetchCommand\x12\x0e.grpcapi.Empty\x1a\x10.grpcapi.Command\x12.\n" +
	"\n" +
	"SendOutput\x12\x10.grpcapi.Command\x1a\x0e.grpcapi.Empty\x12?\n" +
	"\x12RegisterNewImplant\x12\x0e.grpcapi.Empty\x1a\x19.grpcapi.RegisterResponse2z\n" +
	"\x05Admin\x120\n" +
	"\n" +
	"RunCommand\x12\x10.grpcapi.Command\x1a\x10.grpcapi.Command\x12?\n" +
	"\x16ListRegisteredImplants\x12\x0e.grpcapi.Empty\x1a\x15.grpcapi.ImplantsListB\fZ\n" +
	"./;grpcapib\x06proto3"

var (
	file_implant_proto_rawDescOnce sync.Once
	file_implant_proto_rawDescData []byte
)

func file_implant_proto_rawDescGZIP() []byte {
	file_implant_proto_rawDescOnce.Do(func() {
		file_implant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_implant_proto_rawDesc), len(file_implant_proto_rawDesc)))
	})
	return file_implant_proto_rawDescData
}

var file_implant_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_implant_proto_goTypes = []any{
	(*Command)(nil),          // 0: grpcapi.Command
	(*Empty)(nil),            // 1: grpcapi.Empty
	(*ImplantData)(nil),      // 2: grpcapi.ImplantData
	(*ImplantsList)(nil),     // 3: grpcapi.ImplantsList
	(*RegisterResponse)(nil), // 4: grpcapi.RegisterResponse
}
var file_implant_proto_depIdxs = []int32{
	2, // 0: grpcapi.ImplantsList.implants:type_name -> grpcapi.ImplantData
	1, // 1: grpcapi.Implant.FetchCommand:input_type -> grpcapi.Empty
	0, // 2: grpcapi.Implant.SendOutput:input_type -> grpcapi.Command
	1, // 3: grpcapi.Implant.RegisterNewImplant:input_type -> grpcapi.Empty
	0, // 4: grpcapi.Admin.RunCommand:input_type -> grpcapi.Command
	1, // 5: grpcapi.Admin.ListRegisteredImplants:input_type -> grpcapi.Empty
	0, // 6: grpcapi.Implant.FetchCommand:output_type -> grpcapi.Command
	1, // 7: grpcapi.Implant.SendOutput:output_type -> grpcapi.Empty
	4, // 8: grpcapi.Implant.RegisterNewImplant:output_type -> grpcapi.RegisterResponse
	0, // 9: grpcapi.Admin.RunCommand:output_type -> grpcapi.Command
	3, // 10: grpcapi.Admin.ListRegisteredImplants:output_type -> grpcapi.ImplantsList
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_implant_proto_init() }
func file_implant_proto_init() {
	if File_implant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_implant_proto_rawDesc), len(file_implant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_implant_proto_goTypes,
		DependencyIndexes: file_implant_proto_depIdxs,
		MessageInfos:      file_implant_proto_msgTypes,
	}.Build()
	File_implant_proto = out.File
	file_implant_proto_goTypes = nil
	file_implant_proto_depIdxs = nil
}
